### ISSUE TITLE
[PE-D][Tester D] Outdated image in user guide

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103-T16-2/tp#184] opened 2023-11-03 19:54 UTC
![image.png](https://raw.githubusercontent.com/ryanongwx/ped/main/files/1c17854a-ae26-4ed1-8cea-a1ebf25f9dce.png)

UI changed but image in user guide still shows old UI which may be misleading to users, leading them to think that they are using the program wrongly

-------------
Labels: `type.DocumentationBug` `severity.High`
original: ryanongwx/ped#4

**Comment by leezhanpeng** [comment] 2023-11-07 13:03
Duplicate of #172.

**Closed as completed** 2023-11-07 19:45 UTC
Labels: severity.Low, response.Accepted, type.DocumentationBug
